prompt_order=[
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "battery",
    "golang",
    "python",
    "terraform",
    "memory_usage",
    "cmd_duration",
    "line_break",
    "time",
    "character"
]
